---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-config
  namespace: default
data:
  config.json: |
    {
      "prometheus_url": "http://prometheus-server:9090",
      "namespace": "default",
      "control_interval": 30,
      "cooldown_period": 60,
      "ema_alpha": 0.7,
      "min_replicas": 1,
      "max_replicas": 10,
      "rps_thresholds": {
        "1": [10, 0],
        "2": [30, 8],
        "3": [60, 25],
        "4": [100, 50],
        "5": [999999, 90]
      }
    }
